#!/bin/bash
# this file is essential for kicking off the jenkins build on brazos when manos commits to cerebro1055
# manos -> cerebro1055 -> hombros1055 -> brazos
# it must be set to executable!
# provisioned in cerebro1055.rb

curl http://hombros1055:8080/git/notifyCommit?url=git@cerebro1055:/home/hijo.git
