#!/bin/bash
# this file is essential for kicking off the jenkins build on brazos when manos commits to cerebro055
# manos -> cerebro055 -> hombros055 -> brazos
# it must be set to executable!
# provisioned in cerebro055.rb

curl http://hombros055:8080/git/notifyCommit?url=git@cerebro055:/home/hijo.git
