name             'calavera'
maintainer       'Charles Betz'
maintainer_email 'char@erp4it.com'
license          'MIT'
description      'Installs/Configures calavera'
long_description 'Installs/Configures calavera'
version          '0.3.0'
