#Chose 32bit 6.5 for broader compatibility

Vagrant.configure(2) do |config|
 
  config.vm.box = "chef/centos-6.5-i386"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.provision "shell", path: "provision.sh"
  
end
