#Chose 32bit 6.5 for broader compatibility

Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-6.5-i386"
  config.vm.hostname = "manos"
  config.vm.network "private_network", ip: "192.168.33.14"
  config.vm.network "forwarded_port", guest: 80, host: 8084
  config.vm.network "forwarded_port", guest: 8080, host: 8184
  config.vm.synced_folder ".", "/home/calavera"
  config.vm.provision "shell", path: "manos.sh"
  
end
