name             'calavera'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures calavera'
long_description 'Installs/Configures calavera'
version          '0.1.0'

depends           'apt'
#depends           'java'
depends           'tomcat'
depends           'curl'
#depends           'nexus'
depends            'artifactory'
depends           'jenkins'
depends           'ant'
depends           'git'
#depends           'tar-cookbook'
#depends           'hostsfile'   # didn't seem to add value