#Chose 32bit 6.5 for broader compatibility

Vagrant.configure(2) do |config|

  #config.vm.box = "calavera.box"
  config.vm.box = "chef/centos-6.5-i386"
  config.vm.hostname = "cara"
  config.vm.network "private_network", ip: "192.168.33.11", auto_config: false
  config.vm.network "forwarded_port", guest: 22, host: 2201
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "forwarded_port", guest: 8080, host: 8181
  config.vm.synced_folder ".", "/home/calavera"
  config.vm.provision "shell", path: "cara.sh"
  
end
