# here is script for building the calavera.box image
# it takes too long to update and especially to download Java on every vagrant up
# everything always needs Java and Tomcat, so we bake these in as well as an update. 
# path dependent on being run from the CalaveraShared directory.

# this script needs to be ported to Windows as well. 

# prerequisites:
# vagrant locally with the vbguest plugin
# virtualbox locally

echo "it is highly recommended you do a complete vagrant destroy before running this script"
echo "as it destroys and rebuilds the base box all your systems depend on"
# need to make this prettier either with options or a prompt, or at least a wait so they can control-c

mkdir -p initCalavera # make it, stay silent if it already exists
cd initCalavera
echo "---Do not worry about a 'machine not found' error below.---"
vagrant destroy initCalavera --force  # cleanly destroy any previous vagrant
echo "---Do not worry about a 'machine not found' error above.---"
rm -rf *   # now blow it all away

# create provision.sh with update, java and tomcat

touch initCalavera.sh
chmod + initCalavera.sh
echo "### script auto-generated by BakeCalavera.sh" >> initCalavera.sh
echo "apt-get -y update" >> initCalavera.sh
cat ../java.sh >> initCalavera.sh
cat ../tomcat.sh >> initCalavera.sh

touch Vagrantfile

echo "### VagrantFile auto-generated by BakeCalavera.sh"  >> VagrantFile

echo "Vagrant.configure(2) do |config|" >> VagrantFile
echo "   config.vm.box = \"ubuntu/trusty32\"" >> VagrantFile
echo "      config.vm.define \"initCalavera\" do | initCalavera |" >> VagrantFile
echo "      initCalavera.vm.host_name =\"initCalavera\"" >> VagrantFile
echo "      initCalavera.vm.network \"forwarded_port\", guest: 80, host: 8280" >> VagrantFile
echo "      initCalavera.vm.network \"forwarded_port\", guest: 8080, host: 8281" >> VagrantFile
echo "      initCalavera.vm.provision \"shell\", path: \"initCalavera.sh\"" >> VagrantFile
echo "   end" >> VagrantFile
echo "end" >> VagrantFile


# create a vagrant file
echo "---Do not worry about an 'already exists' error below.---"
vagrant box add  ubuntu/trusty32  https://atlas.hashicorp.com/ubuntu/boxes/trusty32
echo "---Do not worry about an 'already exists' error above.---"

vagrant up
 
vagrant package

mv package.box calavera.box   #would be nice to vagrant package -name but bug at time of writing this
vagrant box remove calavera -f
vagrant box add calavera calavera.box -f
rm -f calavera.box
vagrant destroy initCalavera -f
cd ..
rm -rf initCalavera

# now the rest of the vagrant up can be run in the main directory


