name             'hombros'
maintainer       'Charles Betz'
maintainer_email 'char@erp4it.com'
license          'MIT'
description      'Installs/Configures development choreography (e.g. Jenkins)'
long_description ''
version          '0.3.0'

depends           'java'
depends           'tomcat'
depends           'jenkins'