name             'shared'
maintainer       'Charles Betz'
maintainer_email 'char@erp4it.com'
license          'MIT'
description      'cookbook for shared calavera configs'
long_description ''
version          '0.3.0'

#depends           'java8'
depends           'curl'
