name             'brazos'
maintainer       'Charles Betz'
maintainer_email 'char@erp4it.com'
license          'MIT'
description      'cookbook for Jenkins slave server'
long_description ''
version          '0.3.0'

depends           'apt'
depends           'java'
depends           'tomcat'
depends           'ant'
depends           'git'
